name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
      fail-fast: false
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use stable rust toolchain
        run: rustup default stable
      - name: Build
        run: cargo build
      - name: Check Formatting
        run: cargo fmt --check
      - name: Test
        run: cargo test -- --nocapture

